Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> numero1=5
		      
>>> numero2=7
		      
>>> if numero1>numero2:
	print ("El numero 1 es Mayor")
else:
	print ("El numero 2 es Mayor")

>>> ...   File "<stdin>", line 2
    >>> numero2=7
     ^
SyntaxError: invalid syntax
>>> ...   File "<stdin>", line 2
    >>> if numero1>numero2:
     ^
SyntaxError: invalid syntax
>>>   File "<stdin>", line 1
    print ("El numero 1 es Mayor")
    ^
IndentationError: unexpected indent
>>>   File "<stdin>", line 1
    else:
       ^
SyntaxError: invalid syntax
>>>   File "<stdin>", line 1
    print ("El numero 2 es Mayor")
    ^
IndentationError: unexpected indent
>>> >>> 
>>> PRINT ("luis")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PRINT' is not defined
>>> 5+6
11
>>> %10
  File "<stdin>", line 1
    %10
    ^
SyntaxError: invalid syntax
>>> 10%3
1
>>> 5**5
3125
>>> 9//2
4
>>> nombre=5
>>> type (nombre)
<class 'int'>
>>> nombre="luis"
>>> type (nombre)
<class 'str'>
>>> nombre=5.2
>>> type (nombre)
<class 'float'>
>>> mensaje= """Esto es un mensaje
... con tres saltos
... de linea"""
>>> print (mensaje)
Esto es un mensaje
con tres saltos
de linea
>>> numero1=5
>>> numero2=7
>>> if numero1>numero2:
... print ("EL Numero 1 es Mayor")
  File "<stdin>", line 2
    print ("EL Numero 1 es Mayor")
        ^
IndentationError: expected an indented block
>>> print ("EL Numero 1 es Mayor")
EL Numero 1 es Mayor
>>> numero1=5
>>> numero2=7
>>> if numero1>numero2:
... print ("El numero 1 es mayor")
  File "<stdin>", line 2
    print ("El numero 1 es mayor")
        ^
IndentationError: expected an indented block
>>> 
>>> if numero1>numero2:
... print ("El numero 1 es Mayor")
  File "<stdin>", line 2
    print ("El numero 1 es Mayor")
        ^
IndentationError: expected an indented block
>>> numero1=5
>>> numero2=7
>>> if numero1>numero2:
... print("El numero 1 es mayor")
  File "<stdin>", line 2
    print("El numero 1 es mayor")
        ^
IndentationError: expected an indented block
>>> else:
  File "<stdin>", line 1
    else:
       ^
SyntaxError: invalid syntax
>>> numero1=5
>>> numero2=7
>>> if numero1>numero2:
>>>   File "<stdin>", line 1
    >>> numero2=7
     ^
SyntaxError: invalid syntax
>>>   File "<stdin>", line 1
    >>> if numero1>numero2:
     ^
SyntaxError: invalid syntax
>>> numero1=1
>>> numero2=2
>>> if numero 1>numero2:
  File "<stdin>", line 1
    if numero 1>numero2:
              ^
SyntaxError: invalid syntax
>>> numero1=1
>>> numero2=2
>>>   File "<stdin>", line 1
    >>> numero2=2
     ^
SyntaxError: invalid syntax
>>> numero1=1
>>> numero2=2
>>> if numero1>numero2
  File "<stdin>", line 1
    if numero1>numero2
                     ^
SyntaxError: invalid syntax
>>> print ("EL Numero 1 es Mayor")
EL Numero 1 es Mayor
>>> if numero1>numero2
  File "<stdin>", line 1
    if numero1>numero2
                     ^
SyntaxError: invalid syntax
>>> if numero1>numero2
  File "<stdin>", line 1
    if numero1>numero2
                     ^
SyntaxError: invalid syntax
>>> if numero1>numero2